### ISSUE TITLE
SVG fallback needed for Android 2.3 and other older browsers

### ISSUE THREAD

**Issue by capito-tar-gz** [Global-Alliance-for-Local-Voice/Global-Alliance-for-Local-Voice.github.io#1]
https://css-tricks.com/a-complete-guide-to-svg-fallbacks/

**Comment by mkolpack** [comment]
This would be ideal.  But it's lowest priority among all the issues, since this is just the splash page and it will be visible without a fallback for most of the people who will need to see it, such as potential volunteers (especially website developers).

**Comment by capito-tar-gz** [comment]
Delayed for the moment... the site currently doesn't use SVGs.
